steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/justjava-api", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/justjava-api"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "justjava-api",
        "--image",
        "gcr.io/$PROJECT_ID/justjava-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--update-env-vars",
        "_ADMIN_KEY=ADMIN_KEY,_CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME,_CLOUDINARY_API_KEY=CLOUDINARY_API_KEY,_CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET,_DB_URL=DB_URL,_DB_SSL=DB_SSL,_GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID,_REDIS_URL=REDIS_URL",
      ]
images:
  - gcr.io/$PROJECT_ID/justjava-api
