steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/justjava-api", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/justjava-api"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "justjava-api",
        "--image",
        "gcr.io/$PROJECT_ID/justjava-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/$PROJECT_ID/justjava-api
