steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/justjava-api", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/justjava-api"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "justjava-api",
        "--image",
        "gcr.io/$PROJECT_ID/justjava-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--update-env-vars",
        "NODE_ENV=production,ADMIN_KEY=${_ADMIN_KEY},CLOUDINARY_CLOUD_NAME=${_CLOUDINARY_CLOUD_NAME},CLOUDINARY_API_KEY=${_CLOUDINARY_API_KEY},CLOUDINARY_API_SECRET=${_CLOUDINARY_API_SECRET},DB_URL=${_DB_URL},DB_SSL=${_DB_SSL},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},REDIS_URL=${_REDIS_URL},RAVEPAY_ENCRYPTION_KEY=${_RAVEPAY_ENCRYPTION_KEY},RAVEPAY_PUBLIC_KEY=${_RAVEPAY_PUBLIC_KEY},MPESA_CONSUMER_KEY=${_MPESA_CONSUMER_KEY},MPESA_CONSUMER_SECRET=${_MPESA_CONSUMER_SECRET},MPESA_CALLBACK_BASE=${_MPESA_CALLBACK_BASE}",
      ]
images:
  - gcr.io/$PROJECT_ID/justjava-api
