name: test-workflow
on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15.3"
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
